package az.ada.adabank.gui;

import az.ada.adabank.Main;
import az.ada.adabank.entities.Organization;
import java.awt.event.WindowEvent;
import javax.swing.*;

/**
 *
 * @author Ali
 * @author Elnara
 */
public class OrganizationWindow extends JFrame {

    /**
     * Creates new form Organization
     */
    public OrganizationWindow() {
        initComponents();
    }

    public static boolean isNumeric(String str) {
        try {
            double d = Double.parseDouble(str);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        phoneTextField = new JTextField();
        addressTextField = new JTextField();
        vatNumberTextField = new JTextField();
        nameTextField = new JTextField();
        jButton1 = new JButton();

        setResizable(false);
        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("VAT Number");

        jLabel3.setText("Address");

        jLabel4.setText("Phone number");

        phoneTextField.setText("");

        addressTextField.setText("");

        vatNumberTextField.setText(" ");

        nameTextField.setText("");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressTextField, GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(vatNumberTextField)
                                .addComponent(nameTextField)
                                .addComponent(phoneTextField))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(vatNumberTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(addressTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isNumeric(vatNumberTextField.getText()) || isNumeric(nameTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Use correct symbols!");
        } else {
            Organization organization = new Organization();
            organization.setName(nameTextField.getText());
            organization.setVatNumber(vatNumberTextField.getText());
            organization.setPhoneNumber(addressTextField.getText());
            organization.setPhoneNumber(phoneTextField.getText());
            organization.setId(Main.customerIdSequence + "");

            

            Main.customers.put(Main.customerIdSequence, organization);
            Main.customerIdSequence++;
            Dashboard.customersComboBox.addItem(organization.getId() + "::" + organization.getName());
            
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField phoneTextField;
    private JTextField addressTextField;
    private JTextField vatNumberTextField;
    private JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
